# Generated by Django 4.2.2 on 2023-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_amazon', '0003_alter_photo_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='item_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
