# Generated by Django 4.2.2 on 2023-06-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_amazon', '0004_alter_photo_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='User',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=70)),
                ('item_owner', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(max_length=1024)),
                ('item_picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_amazon.photo')),
            ],
        ),
    ]
