# Generated by Django 4.2.2 on 2023-06-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_amazon', '0005_alter_photo_user_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='User',
            new_name='user',
        ),
    ]
