# Generated by Django 4.1.7 on 2023-03-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
