# Generated by Django 4.0.10 on 2023-05-14 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='coinrequest',
            name='status',
            field=models.CharField(choices=[('a', 'available'), ('r', 'reserved'), ('u', 'unknown')], default='u', max_length=1),
        ),
        migrations.AddField(
            model_name='coinrequest',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.sectorcoin'),
        ),
    ]
