# Generated by Django 4.0.10 on 2023-05-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
